#!/bin/bash


# if [ ! "$#" == "5" ]
# then
#   echo "Usage ./extract_scaling.sh <max-n-cores> <crunch-sigma-percent> <lazy-unpack> <trigger-unpacking> <input-file>"
#   echo "Example:  ./extract_scaling.sh 40 0.1 true true /path/to/lcio-file.slcio"
#   exit 1
# fi

function printUsage() {
  echo "Usage:"
  echo "run-benchmarking [options] --inputfile <slcio-file>"
  echo ""
  echo "Run MarlinMT for multi-core benchmarking"
  echo ""
  echo "Options:"
  echo "  --mincores <int>           The start number of cores [default=2]"
  echo "  --maxcores <int>           The end number of cores [default=2]"
  echo "  --mincrunch <int>          The start crunch time (ms) [default=500]"
  echo "  --maxcrunch <int>          The end crunch time (ms) [default=1000]"
  echo "  --crunchstep <int>         The step in crunch time numbers [default=500]"
  echo "  --sigmacrunch <float>      Introduce an event-by-event gaussian random"
  echo "                             fluctuation in the crunch time [default=0]"
  echo "  --inputfile <slcio-file>   The LCIO input file. Mandatory parameter !"
  echo "  --lazy                     Whether use option LazyUnpack for LCIO reading [default=false]"
  echo "  --trigger                  Whether to trigger the event unpacking in worker threads [default=false]"
  echo "  -h --help                  Print help and exit"
  echo ""
}


if [ -z "$MARLIN_DIR" ]
then
  echo "MARLIN_DIR not set. Please setup your environment!"
  exit 1
fi

if [ -z "$LCIO_DIR" ]
then
  echo "LCIO_DIR not set. Please setup your environment!"
  exit 1
fi

OPTS=`getopt -o h -l mincores:,maxcores:,mincrunch:,maxcrunch:,crunchstep:,sigmacrunch:,inputfile:,minhistcrunch:,maxhistcrunch:,histcrunchstep:,histsigmapercent:,nbins:,nhists:,nfills:,memorylayout:,steeringfile:,lazy,trigger,help -n 'parse-options' -- "$@"`
eval set -- "$OPTS"

# general configuration
mincores=2
maxcores=2
lazyUnpack="false"
triggerUnpacking="false"
inputfile=""
steeringfile=${MARLIN_DIR}/benchmarking/cpu_crunching.xml

# cpu_crunch configuration
mincrunch=500
maxcrunch=500
crunchstep=500
sigmapercent=0

# histogram processor configuration
minhistcrunch=$mincrunch
maxhistcrunch=$maxcrunch
histcrunchstep=$crunchstep
histsigmapercent=$sigmapercent
nbins=1000
nhists=10
nfills=1000
memorylayout="Copy"


while true; do
  case "$1" in
	# general configuration
    --mincores ) mincores=$2; shift; shift ;;
    --maxcores ) maxcores=$2; shift; shift ;;
    --inputfile ) inputfile=$2; shift; shift ;;
    --lazy ) lazyUnpack="true"; shift ;;
    --trigger ) triggerUnpacking="true"; shift ;;
		--steeringfile ) steeringfile=$2; shift; shift;;
	# cpu crunch configuration
    --mincrunch ) mincrunch=$2; shift; shift ;;
    --maxcrunch ) maxcrunch=$2; shift; shift ;;
    --crunchstep ) crunchstep=$2; shift; shift ;;
    --sigmacrunch ) sigmacrunch=$2; shift; shift ;;
	# histogram processor configuration
		--minhistcrunch ) minhistcrunch=$2; shift; shift ;;
		--maxhistcrunch ) maxhistcrunch=$2; shift; shift ;;
		--histcrunchstep ) histcrunchstep=$2; shift; shift ;;
		--histsigmapercent ) histsigmapercent=$2; shift; shift ;;
		--nbins ) nbins=$2; shift; shift ;;
		--nhists ) nhists=$2; shift; shift ;;
		--nfills ) nfills=$2; shift; shift ;;
		--memorylayout ) memorylayout=$2; shift; shift ;;
	# other inputs
    -h | --help )  printUsage; exit 0 ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done


if [ "$inputfile" == "" ]
then
  echo "ERROR: --inputfile argument is mandatory"
  printUsage
  exit 1
fi

cores=`seq ${mincores} ${maxcores} | tr '\n' ' '`
crunchtimes=`seq ${mincrunch} ${crunchstep} ${maxcrunch} | tr '\n' ' '`
histcrunchtimes=`seq ${minhistcrunch} ${histcrunchstep} ${maxhistcrunch} | tr '\n' ' '`

lazyUnpackStr=""
triggerUnpackingStr=""

if [ "${lazyUnpack}" == "true" ]
then
  lazyUnpackStr="lazy"
else
  lazyUnpackStr="nolazy"
fi

if [ "${triggerUnpacking}" == "true" ]
then
  triggerUnpackingStr="trig"
else
  triggerUnpackingStr="notrig"
fi

output="MarlinMTBenchmarking_Lazy.${lazyUnpackStr}_Trigger.${triggerUnpackingStr}_Sigma.${sigmapercent}.txt"

if [ -f ${output} ]
then
  rm ${output}
fi

echo "Running with following settings:"
echo "  - n cores: ${cores}"
echo "  - crunch times: ${crunchtimes}"
echo "  - crunch sigma percentage: $sigmapercent"
echo "  - lazy unpacking ? $lazyUnpack"
echo "  - trigger unpacking ? $triggerUnpacking"
echo "  - LCIO input file: $inputfile"
echo "  - Marlin steering file: $steeringfile"
echo "  - Benchmark output file: $output"

# load the file in the cache for next
echo "Loading input file into cache: ${inputfile}"
anajob ${inputfile} >> /dev/null

echo "Start benchmarking ..."
for c in ${cores}
do
  for cr in ${crunchtimes}
  do
		crunchSigma=`echo "(${cr}*${sigmapercent})" | bc`
		for hcr in ${histcrunchtimes}
		do
			hCrunchSigma=`echo "(${hcr}*${histsigmapercent})" | bc`
			echo "Running MarlinMT with:"
			echo "  general:"
			echo "  -- N cores:            ${c}"
			echo "  -- Lazy unpacking:     ${lazyUnpack}"
			echo "  -- Trigger unpacking:  ${triggerUnpacking}"
			echo "  cpu_crunch:"
			echo "  -- Crunch time:        ${cr}"
			echo "  -- Crunch sigma:       ${crunchSigma}"
			echo "  histogram filling:"
			echo "  -- number histograms:  ${nhists}"
			echo "  -- number bins:        ${nbins}"
			echo "  -- number fills:       ${nfills}"
			MarlinMT \
			${steeringfile} \
			--constant.TriggerUnpacking="${triggerUnpacking}" \
			--datasource.LCIOInputFiles="${inputfile}" \
			--datasource.LazyUnpack="${lazyUnpack}" \
			--CPUCrunch.CrunchTime=${cr} \
			--CPUCrunch.CrunchSigma=${crunchSigma} \
			--HistFilling.NBins=${nbins} \
			--HistFilling.NHists=${nhists} \
			--HistFilling.NFills=${nfills} \
			--HistFilling.CrunchTime=${hcr} \
			--HistFilling.CrunchSigma=${hCrunchSigma} \
			--global.Verbosity=MESSAGE \
			--global.Concurrency=${c} > scaling_temp_$$.log 
			serial=$( cat scaling_temp_$$.log | grep serial | awk '{print $7}' )
			parallel=$( cat scaling_temp_$$.log |  grep serial | awk '{print $9}' )
			scaling=$( cat scaling_temp_$$.log | grep serial| awk '{print $11}' )
			echo "Result: ${c} ${cr} ${crunchSigma} ${serial} ${parallel} ${scaling}"
			echo "${c} ${cr} ${crunchSigma} ${serial} ${parallel} ${scaling}" >> ${output}
			echo ""
		done
  done
done
